#pragma once
#include "IGDDeviceImp.h"
#include "IGDInstanceImp.h"
#include "IGDMemoryAllocatorImp.h"
#include "IGDPhysicalDeviceGroupImp.h"
#include "IGDPhysicalDeviceImp.h"
#include "IGDQueueImp.h"
#include "IGDSwapChainImp.h"
#include "IGDSystemImp.h"