#pragma once
#if DEVILX_RENDERSYSTEM_D3D11_MODE==DEVILX_RENDERSYSTEM_D3D11_ST
#include "D3D11RenderTaskST.h"
#elif DEVILX_RENDERSYSTEM_D3D11_MODE==DEVILX_RENDERSYSTEM_D3D11_MT
#include "D3D11RenderTaskMT.h"
#elif DEVILX_RENDERSYSTEM_D3D11_MODE==DEVILX_RENDERSYSTEM_D3D11_MT_DS
#include "D3D11RenderTaskMTDS.h"
#endif