#pragma once
#include "Utility.h"
#include "IGameCamera.h"
#include "IGameComponent.h"
#include "IGameEnum.h"
#include "IGameLight.h"
#include "IGameObject.h"
#include "IGameScene.h"
#include "IGameSceneNode.h"