#pragma once
#if DEVILX_RENDERSYSTEM_GLES3_MODE==DEVILX_RENDERSYSTEM_GLES3_ST
#include "GLES3RenderTaskST.h"
#elif DEVILX_RENDERSYSTEM_GLES3_MODE==DEVILX_RENDERSYSTEM_GLES3_MT
#include "GLES3RenderTaskMT.h"
#endif