#pragma once
#include "CommonThirdPart.h"
#include "CommonSTD.h"
#include "CommonPlatformInclude.h"

#include "CommonDefine.h"
#include "CommonPlatformDefine.h"
#include "CommonType.h"
#include "CommonConstant.h"
#include "CommonStruct.h"

#include "CommonAngle.h"
#include "CommonAny.h"
#include "CommonBounding.h"
#include "CommonBoundingTreeNode.h"
#include "CommonColour.h"
#include "CommonCommandQueue.h"
#include "CommonDirtyFlagContainer.h"
#include "ICommonUserDataContainerImp.h"
#include "CommonMath.h"
#include "CommonMatrix.h"
#include "CommonMessageMode.h"
#include "CommonNode.h"
#include "CommonOctree.h"
#include "CommonPathUtility.h"
#include "CommonPlane.h"
#include "CommonPointer.h"
#include "CommonRange.h"
#include "CommonRay.h"
#include "CommonRect.h"
#include "CommonReferenceObject.h"
#include "CommonResourceContainer.h"
#include "CommonSingleton.h"
#include "CommonStringUtility.h"
#include "CommonTransformNode.h"
#include "CommonTreeContainer.h"
#include "CommonUserDataContainer.h"
#include "CommonUTFChar.h"
#include "CommonUTFString.h"
#include "CommonUtility.h"
#include "CommonVector.h"
#include "CommonVectorF.h"
#include "CommonVectorI.h"

#include "ICommonGraphicsCommon.h"
#include "ICommonGraphicsBuffer.h"
#include "ICommonGraphicsDevice.h"
#include "ICommonGraphicsInputLayout.h"
#include "ICommonGraphicsTexture.h"

#include "CommonD3D9GraphicsDeviceImp.h"

#include "CommonD3D11GraphicsBufferImp.h"
#include "CommonD3D11GraphicsDeviceImp.h"

#include "CommonGLGraphics.h"
#include "CommonGLGraphicsBufferImp.h"
#include "CommonGLGraphicsDeviceImp.h"
#include "CommonGLGraphicsInputLayoutImp.h"
#include "CommonGLGraphicsTextureImp.h"