#pragma once
#define DEVILX_OPERATING_SYSTEM_UNKNOWN 0
#define DEVILX_OPERATING_SYSTEM_WINDOWS 1
#define DEVILX_OPERATING_SYSTEM_LINUX 2
#define DEVILX_WINDOW_SYSTEM_UNKNOWN 0
#define DEVILX_WINDOW_SYSTEM_WINDOWS 1
#define DEVILX_WINDOW_SYSTEM_X 2
#define DEVILX_WINDOW_SYSTEM_ANDROID 3
#if defined(_MSC_VER)
#define DEVILX_OPERATING_SYSTEM DEVILX_OPERATING_SYSTEM_WINDOWS
#define DEVILX_WINDOW_SYSTEM DEVILX_WINDOW_SYSTEM_WINDOWS
#endif
#ifdef DEVILX_ANDROID
#define DEVILX_OPERATING_SYSTEM DEVILX_OPERATING_SYSTEM_LINUX
#define DEVILX_WINDOW_SYSTEM DEVILX_WINDOW_SYSTEM_ANDROID
#endif
#ifndef DEVILX_OPERATING_SYSTEM
#error("DEVILX_OPERATING_SYSTEM is not defined!!!")
#endif
#ifndef DEVILX_WINDOW_SYSTEM
#error("DEVILX_WINDOW_SYSTEM is not defined!!!")
#endif