#pragma once
#if DEVILX_RENDERSYSTEM_GL4_MODE==DEVILX_RENDERSYSTEM_GL4_ST
#include "GL4RenderTaskST.h"
#elif DEVILX_RENDERSYSTEM_GL4_MODE==DEVILX_RENDERSYSTEM_GL4_MT
#include "GL4RenderTaskMT.h"
#endif