#pragma once
#include "IInputEnum.h"
#include "IInputPhysicalDevice.h"
#include "IInputPhysicalDeviceManager.h"
#include "IInputSystem.h"
#include "IInputVirtualDevice.h"
#include "IInputVirtualDeviceManager.h"
#include "IKeyboard.h"
#include "IMouse.h"