#pragma once
#include "ICoreGACommandList.h"
#include "ICoreGACommandQueue.h"
#include "ICoreGADevice.h"
#include "ICoreGAManager.h"
#include "ICoreGAEnum.h"
#include "ICoreGAResource.h"
#include "ICoreGAStruct.h"
#include "ICoreGAView.h"
